name: ci

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  ci:
    uses: compliance-framework/workflows/.github/workflows/ci-policies.yml@a94553bdc479fac47fbea7febbf57dcb615dbc87
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
    secrets: inherit

  notify:
    needs: [ci]
    if: failure()
    uses: compliance-framework/workflows/.github/workflows/notify-failure.yml@a94553bdc479fac47fbea7febbf57dcb615dbc87
    with:
      workflows-ref: a94553bdc479fac47fbea7febbf57dcb615dbc87
    permissions:
      actions: read
      contents: read
    secrets: inherit
