name: ci

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
  push:
    branches: [main]

permissions: {}

jobs:
  ci:
    uses: compliance-framework/workflows/.github/workflows/ci-policies.yml@0820491954d2f748fed5601109a8b6e422deee69 # v1.1.0
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
    secrets: inherit

  release-checks:
    uses: compliance-framework/workflows/.github/workflows/release-checks.yml@0820491954d2f748fed5601109a8b6e422deee69 # v1.1.0
    permissions:
      contents: read

  notify:
    needs: [ci, release-checks]
    if: always()
    uses: compliance-framework/workflows/.github/workflows/notify-failure.yml@0820491954d2f748fed5601109a8b6e422deee69 # v1.1.0
    with:
      needs: ${{ toJSON(needs) }}
    permissions:
      contents: read
    secrets: inherit
